### ISSUE TITLE
Changing nginx upload limit

### ISSUE THREAD

**Issue by dcvz** [refunc/refunc#13]
At the moment I'm trying to test out `refunc` and am getting an error when uploading the lambda:

```
An error occurred (413) when calling the CreateFunction operation: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.15.12</center>
</body>
</html>
```

I assume that this is coming from nginx who's default upload limit is 1Mb (or maybe [this](https://github.com/refunc/refunc/blob/master/cmd/play/template.go#L54)).
Does `refunc` provide a way to increase this? If not how can we use a custom template?

**Comment by dcvz** [comment]
I've attempted to get past this error by using the [The Refunc Way](https://github.com/refunc/refunc#the-refunc-way) with the following configuration:

```yaml
---
#./function.yaml
apiVersion: k8s.refunc.io/v1beta3
kind: Funcdef
metadata:
  name: dshooks
spec:
  body: base64://.serverless/dshooks.zip
  entry: lambda_function.lambda_handler
  hash: 553c10515b3d7abf77519eada39c744fb091fc82
  maxReplicas: 1
  runtime:
    name: nodejs8.10
    envs:
      NODE_ENV: 'production'
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
    timeout: 30---
#./simplehttp.yaml
apiVersion: k8s.refunc.io/v1beta3
kind: Trigger
metadata:
  name: http-dshooks
spec:
  funcName: dshooks
  type: httptrigger
---
#./xenv.yaml
apiVersion: k8s.refunc.io/v1beta3
kind: Xenv
metadata:
  name: nodejs8.10
spec:
  type: lambda
  transport: nats
  poolSize: 1
  container:
    image: refunc/lambda:nodejs8.10
    imagePullPolicy: IfNotPresent

```

It's not complaining about the upload now however, it doesn't find the lambda when I try to invoke it -- which leads me to believe its not actually uploading but I don't get any errors when running: `kubectl create -n refunc-play -f inone.yml`.

How do we pass a local path for a `zip` file in the `body:` key of the `Funcdef`?
