### ISSUE TITLE
Funcdef body point to local zip

### ISSUE THREAD

**Issue by dcvz** [refunc/refunc#14]
I've attempted to use the [The Refunc Way](https://github.com/refunc/refunc#the-refunc-way) with the following configuration:

```yaml
---
#./function.yaml
apiVersion: k8s.refunc.io/v1beta3
kind: Funcdef
metadata:
  name: dshooks
spec:
  body: base64://.serverless/dshooks.zip
  entry: src/lambda.handler
  hash: 553c10515b3d7abf77519eada39c744fb091fc82
  maxReplicas: 1
  runtime:
    name: nodejs8.10
    envs:
      NODE_ENV: 'production'
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
    timeout: 30---
#./simplehttp.yaml
apiVersion: k8s.refunc.io/v1beta3
kind: Trigger
metadata:
  name: http-dshooks
spec:
  funcName: dshooks
  type: httptrigger
---
#./xenv.yaml
apiVersion: k8s.refunc.io/v1beta3
kind: Xenv
metadata:
  name: nodejs8.10
spec:
  type: lambda
  transport: nats
  poolSize: 1
  container:
    image: refunc/lambda:nodejs8.10
    imagePullPolicy: IfNotPresent

```

The console spits out:

```
trigger.k8s.refunc.io/http-dshooks created
xenv.k8s.refunc.io/nodejs8.10 created
```

It's not complaining about the upload; however, it doesn't find the lambda when I try to invoke it -- which leads me to believe its not actually uploading but I don't get any errors when running: `kubectl create -n refunc-play -f inone.yml`.

How do we pass a local path for a `zip` file in the `body:` key of the `Funcdef`?
